config/routes.rb
Gmapstest::Application.routes.draw do
	resources :homes
        resources :myaddresses
 
  
   root :to => 'homes#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/address_list.rb
class AddressList < ActiveRecord::Base
   
end

app/models/myaddress.rb
class Myaddress < ActiveRecord::Base
  # attr_accessible :title, :body
 attr_accessible :country, :city, :latitude, :longitude, :gmaps
   validates :country, :presence => true

 acts_as_gmappable 

def gmaps4rails_address
  "#{self.city}" 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
	
  end

end

app/controllers/myaddresses_controller.rb
class MyaddressesController < ApplicationController
def new
@address=Myaddress.new
end

def create
@address=Myaddress.new(params[:myaddress])
if @address.save 
redirect_to myaddresses_path
else
render 'new'
end
end

def index
@addresses = Myaddress.all
@json = @addresses.to_gmaps4rails
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/myaddresses_helper.rb
module MyaddressesHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>


<%= link_to "new", new_myaddress_path %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmapstest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%#= stylesheet_link_tag    "gmaps4rails" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

<%= yield :scripts %>
</body>

</html>

app/views/myaddresses/index.html.erb
<% @addresses.each do |a| %>
<%= a.city %><br/>
<%= a.country %><br/>
<%= a.longitude %><br/>
<%= a.latitude %><br/>
<% end %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'>
  <%= gmaps4rails(@json) %>>
</div>
</div>

app/views/myaddresses/new.html.erb
<%= form_for @address do |f|%>
City: <%= f.text_field :city %><br/>
Country: <%= f.text_field :country %>
<%= f.submit "save"%>
<% end %>